apiVersion: apps/v1
kind: Deployment
metadata:
  name: vote-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      appname: vote-worker
  template:
    metadata:
      labels:
        appname: vote-worker
    spec:
      containers:
        - name: vote-worker
          image: brindilsz/vote-worker:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 8080

---
apiVersion: v1
kind: Service
metadata:
  labels:
    appname: vote-worker
  name: vote-worker
  annotations:
spec:
  type:  NodePort
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
  selector:
    appname: vote-worker
