node ('main'){
    stage('Checkout') {
        git url: 'https://github.com/jenarutamara/swarm-microservice-demo-v1.git', branch: 'master', credentialsId: 'github'
        gitCommitId = sh(returnStdout: true, script: 'git rev-parse --verify HEAD').trim()
        parameterTemplatedeployment(gitCommitId)
    }
    
    stage('Build') {
        sh """
        docker build -t brindilsz/vote-worker:latest https://github.com/jenarutamara/swarm-microservice-demo-v1.git#master:vote-worker
        """
    }
    
    
     stage('PushPush'){
        withCredentials([usernamePassword( credentialsId: 'registry', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
          sh """
          docker login -u ${USERNAME} -p ${PASSWORD}
          docker push brindilsz/vote-worker:latest    
          """
        }
        

    }
    stage ('DeployToCluster'){
        sh """
            kubectl apply -f ./vote-worker/deployment.yaml -n microservice-demo-v1
        """
    }
  
}

def parameterTemplatedeployment(gitCommitId ) {
    parameter = readFile('./vote-worker/deployment.yaml')
    parameter = parameter.replaceAll('\\$GIT_COMMIT_ID', gitCommitId)

    writeFile file: './vote-worker/deployment.yaml', text: parameter
}
