node ('main'){
    stage('Checkout') {
        git url: 'https://github.com/jenarutamara/swarm-microservice-demo-v1.git', branch: 'master', credentialsId: 'github'
    }
    
    stage('Build') {
        sh """
        docker build -t brindilsz/vote-worker:latest https://github.com/jenarutamara/swarm-microservice-demo-v1.git#master:vote-worker
        """
    }
    
    
     stage('PushPush'){
        withCredentials([usernamePassword( credentialsId: 'registry', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
          sh """
          docker login -u ${USERNAME} -p ${PASSWORD}
          docker push brindilsz/vote-worker:latest    
          """
        }
        

    }
    stage ('DeployToCluster'){
        sh """
            kubectl apply -f ./vote-worker/deployment.yaml -n microservice-demo-v1
        """
    }
  
}  
