apiVersion: apps/v1
kind: Deployment
metadata:
  name: store
spec:
  replicas: 1
  selector:
    matchLabels:
      appname: store
  template:
    metadata:
      labels:
        appname: store
        gitcommitid: $GIT_COMMIT_ID
    spec:
      containers:
        - name: store
          image: brindilsz/postgres:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 5432

---
apiVersion: v1
kind: Service
metadata:
  labels:
    appname: store
  name: store
  annotations:
spec:
  type:  NodePort
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
  selector:
    appname: store
