apiVersion: apps/v1
kind: Deployment
metadata:
  name: redis01
spec:
  replicas: 1
  selector:
    matchLabels:
      appname: redis01
  template:
    metadata:
      labels:
        appname: redis01
        app: redis01
        gitcommitid: $GIT_COMMIT_ID
    spec:
      containers:
        - name: redis01
          image: brindilsz/redis:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 6379

---
apiVersion: v1
kind: Service
metadata:
  labels:
    appname: redis01
  name: redis01
  annotations:
spec:
  type:  NodePort
  ports:
    - port: 6379
      targetPort: 6379
      protocol: TCP
  selector:
    appname: redis01
