node ('main'){
    stage('Checkout') {
        git url: 'https://github.com/jenarutamara/swarm-microservice-demo-v1.git', branch: 'master', credentialsId: 'github'
        gitCommitId = sh(returnStdout: true, script: 'git rev-parse HEAD').trim()
        parameterTemplatedeployment(gitCommitId)
    }
    
    stage('Build') {
        sh """
        docker build -t brindilsz/redis:latest https://github.com/jenarutamara/swarm-microservice-demo-v1.git#master:redis
        """
    }
    
    
     stage('PushPush'){
        withCredentials([usernamePassword( credentialsId: 'registry', usernameVariable: 'USERNAME', passwordVariable: 'PASSWORD')]) {
          sh """
          docker login -u ${USERNAME} -p ${PASSWORD}
          docker push brindilsz/redis:latest    
          """
        }
        

    }
    stage ('DeployToCluster'){
        sh """
            kubectl apply -f ./redis/deployment.yaml -n microservice-demo-v1
        """
    }
  
}

def parameterTemplatedeployment(gitCommitId ) {
    parameter = parameter.replaceAll('\\$GIT_COMMIT_ID', gitCommitId)

    writeFile file: './redis/deployment.yaml', text: parameter
}
